[tool.poetry]
name = "arquivos"
version = "1"
description = ""
authors = ["guilherme jonck"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
